# Generated by Django 3.1.2 on 2020-12-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatTurnira', models.CharField(default='', max_length=100)),
                ('vrijemePocetka', models.DateTimeField()),
                ('vrijemeZavrsetka', models.DateTimeField()),
                ('brojSudionika', models.IntegerField()),
                ('vidljivost', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijemePocetka', models.DateTimeField()),
                ('vrijemeZavrsetka', models.DateTimeField()),
                ('opisTreninga', models.CharField(default='', max_length=100)),
                ('vidljivost', models.BooleanField(default=1)),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transakcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumTransakcije', models.DateField()),
                ('iznosUplate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taktika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('initConfig', models.CharField(max_length=100)),
                ('movesWhite', models.CharField(max_length=3000)),
                ('movesBlack', models.CharField(max_length=3000)),
                ('tezina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brojGlasova', models.IntegerField()),
                ('validnost', models.BooleanField(default=1)),
                ('vidljivost', models.BooleanField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RjesenjeTaktike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taktika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SahovskiKlub.taktika')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RangLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodovi', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrijavaTurnir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SahovskiKlub.turnir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrijavaTrening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SahovskiKlub.trening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Novost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijemeObjave', models.DateTimeField()),
                ('naslov', models.CharField(default='', max_length=100)),
                ('tekst', models.CharField(default='', max_length=3000)),
                ('vidljivost', models.BooleanField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DojavaPogreske',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prihvacena', models.BooleanField()),
                ('predlozeniTijek', models.CharField(default='', max_length=6000)),
                ('opis', models.CharField(default='', max_length=3000)),
                ('taktika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SahovskiKlub.taktika')),
                ('userDojave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userRevizija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDojave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aktivnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijemeAktivnosti', models.DateTimeField()),
                ('aktivnost', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
