# Generated by Django 3.1.2 on 2020-12-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SahovskiKlub', '0002_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prijavaturnir',
            old_name='trening',
            new_name='turnir',
        ),
        migrations.AddField(
            model_name='taktika',
            name='ime',
            field=models.CharField(default='default ime', max_length=50),
        ),
        migrations.AddField(
            model_name='trening',
            name='ime',
            field=models.CharField(default='default ime', max_length=50),
        ),
        migrations.AddField(
            model_name='turnir',
            name='ime',
            field=models.CharField(default='default ime', max_length=50),
        ),
        migrations.AlterField(
            model_name='dojavapogreske',
            name='prihvacena',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
