# Generated by Django 3.1.2 on 2020-12-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SahovskiKlub', '0003_refaktoriranje'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnir',
            name='organizator',
            field=models.ForeignKey(default='fejkJuzer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
