# Generated by Django 3.1.2 on 2020-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SahovskiKlub', '0004_turnir_organizator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodovi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.IntegerField()),
                ('bodovi', models.IntegerField()),
            ],
            options={
                'db_table': 'sahovskiklub_bodovi',
                'managed': False,
            },
        ),
    ]
